// Generated by XMI Compiler v0.1 — do not edit manually.
// Source: libs/user/core/model.xmi
// Regenerate: npx nx run @svx/user-core:compile-xmi

import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Reflectable, Implements } from '@svx/common';
import { AddressSchema } from './entity-schemas';
import { UserEntity } from './user.entity';

/** A physical address associated with a user. */
@Reflectable() @Implements(AddressSchema) @Entity("ADDRESS")
export class AddressEntity {
  /** Auto-generated primary key. */
  @PrimaryGeneratedColumn({ name: "ID" })
  id?: number;
  
  /** Name of the city. */
  @Column({ name: "CITY", type: "varchar", length: 100 })
  city!: string;
  
  /** The user this address belongs to. */
  @ManyToOne(() => UserEntity, (user: UserEntity) => user.addresses, { onDelete: 'CASCADE' })
  @JoinColumn({ name: "OR_USER", foreignKeyConstraintName: "FK_ADDRESS_USER" })
  user!: UserEntity;
  
}