// Generated by XMI Compiler v0.1 — do not edit manually.
// Source: libs/user/core/model.xmi
// Regenerate: npx nx run @svx/user-core:compile-xmi

import { array, integer, object, optional, string } from '@svx/common';
import type { InferObject } from '@svx/common';

/** Short text field — max 100 characters. */
export const SmallString = string().max(100);

/** A physical address associated with a user. */
export const AddressSchema = object({
  id: optional(integer()),
  city: SmallString,
}, 'Address');

/** A registered user of the platform. */
export const UserSchema = object({
  id: optional(integer()),
  name: SmallString,
  email: string().max(200),
  addresses: array(AddressSchema),
}, 'User');

export type AddressType = InferObject<typeof AddressSchema>
export type UserType = InferObject<typeof UserSchema>