// Generated by XMI Compiler v0.1 — do not edit manually.
// Source: libs/user/core/model.xmi
// Regenerate: npx nx run @svx/user-core:compile-xmi

import { Column, Entity, OneToMany, PrimaryGeneratedColumn } from 'typeorm';
import { Reflectable, Implements } from '@svx/common';
import { UserSchema } from './entity-schemas';
import { AddressEntity } from './address.entity';

/** A registered user of the platform. */
@Reflectable() @Implements(UserSchema) @Entity("USER")
export class UserEntity {
  /** Auto-generated primary key. */
  @PrimaryGeneratedColumn({ name: "ID" })
  id?: number;
  
  /** Display name of the user. */
  @Column({ name: "NAME", type: "varchar", length: 100 })
  name!: string;
  
  /** Unique email address used for login. */
  @Column({ name: "EMAIL", type: "varchar", length: 200, default: "" })
  email!: string;
  
  /** Delivery and billing addresses belonging to this user. */
  @OneToMany(() => AddressEntity, (address: AddressEntity) => address.user, { cascade: true })
  addresses!: AddressEntity[];
  
}